### ISSUE TITLE
PlatformIO configuration

### ISSUE THREAD

**Issue by mars3142** [01Space/ESP32-S3-0.42OLED#3]
What are the settings for PlatformIO? I can compile and install the GraphicsTest via the Arduino IDE and it runs perfect. If I compile with PlatformIO and upload the binary it won't run. 

```
[env:esp32-s3-0.42oled]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
lib_ldf_mode = deep
lib_deps = 
   kitesurfer1404/WS2812FX@^1.4.1
   olikraus/U8g2@^2.34.15
```

This isn't working. Does someone has a platformio.ini example for me?

**Comment by mars3142** [comment]
One solution is to change the board to 

```
board = adafruit_feather_esp32s3
```

Because it has only 4MB Flash and not 8MB like the **esp32-s3-devkitc-1**.

Another solution is to rewrite the partition table, but this will be more complicated.

**Comment by 01Space** [comment]
I updated the schematic diagram and used the ESP32-S3FN4R2 chip，

**Comment by 01Space** [comment]
https://www.lilygo.cc/products/t-qt-pro  You can try to use this setting. They use the same chip

**Comment by mars3142** [comment]
Ah, I see. They use a custom board.json... Maybe I'll create a PR for your project, if I got it working.

**Comment by 01Space** [comment]
thank you!
